### ISSUE TITLE
后端-帖子点赞按钮组件功能实现

### ISSUE THREAD

**Issue by luuuYkl** [luuuYkl/FawnFlock#11]
给出链接，实现前端对数据库中posts表的like_count列的内容的读取以及修改。
功能详细实现：
1.点赞数量显示：读取posts表的like_count列的内容
2.点赞数修改：用户点击按钮后posts表的like_count的数量+1

**Comment by tcirtsa** [comment]
获取like_count: 可以使用接口：posts/{post id}，里面传来的包括了数据库表所有对应字段的数据，也可以使用posts/{post id}/like_count只获得count

**Comment by tcirtsa** [comment]
获取like_count: 可以使用接口：posts/<post id>，里面传来的包括了数据库表所有对应字段的数据，也可以使用posts/<post id>/like_count只获得count

**Comment by tcirtsa** [comment]
点赞数修改：接口posts/{post id}/like/{user_id}，method使用post就是add，使用delete就是减少
