### ISSUE TITLE
后端-评论按钮组件的功能实现

### ISSUE THREAD

**Issue by luuuYkl** [luuuYkl/FawnFlock#12]
给出链接，实现对后端数据库的posts表的comment_count的读取

**Comment by tcirtsa** [comment]
获取like_count: 可以使用接口：posts/{post id}，里面传来的包括了数据库表所有对应字段的数据，也可以使用posts/{post id}/comment_count只获得count

**Comment by tcirtsa** [comment]
获取like_count: 可以使用接口：posts/{post id}，里面传来的包括了数据库表所有对应字段的数据，也可以使用posts/{post id}/comment_count只获得count
