### ISSUE TITLE
后端-点赞数传输和读取

### ISSUE THREAD

**Issue by luuuYkl** [luuuYkl/FawnFlock#8]
https://github.com/luuuYkl/FawnFlock/blob/6fb8b895e8fe18dc4279074e3ad72ec7468e38d5/src/components/posts/LikeButton.vue#L35

**Comment by tcirtsa** [comment]
查询点赞数:/posts/<post_id>/like_count

**Comment by tcirtsa** [comment]
点赞和取消点赞：/posts/<post_id>/like/<user_id>
